# Generated by Django 3.1.7 on 2021-04-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210430_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit')),
                ('taille', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.taille')),
            ],
        ),
    ]
