# Generated by Django 3.1.7 on 2021-04-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_couleur_detail_produit_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_produit',
            name='couleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.couleur'),
        ),
        migrations.AlterField(
            model_name='detail_produit',
            name='taille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.taille'),
        ),
    ]
