# Generated by Django 3.1.7 on 2021-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210430_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='ancienPrix',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
    ]
