# Generated by Django 3.1.7 on 2021-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
