# Generated by Django 3.1.7 on 2021-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_panier_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='taille',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
