# Generated by Django 3.1.7 on 2021-05-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_commande_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='paiment',
            new_name='paiement',
        ),
    ]
