# Generated by Django 3.1.7 on 2021-05-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210510_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.panier'),
        ),
    ]
