# Generated by Django 3.1.7 on 2021-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_commande_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='panier',
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.CharField(default='PRODUIT', max_length=200),
        ),
    ]
