# Generated by Django 3.1.7 on 2021-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210511_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
